dist: trusty
sudo: required
language: cpp
compiler:
- clang
- gcc

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libcurl4-openssl-dev libexpat-dev subversion darcs mercurial cvs cssc bzr rcs

script:
- ./autogen.sh
- ./configure
- make
- VERBOSE=true make check
