#! /bin/bash
set -e
set -x

remote() {
  ssh $1 "cd _builds && $2"
}

make distcheck

PACKAGE=`perl -ne '/^PACKAGE\s*=\s*(\S+)/ && print "$1";' Makefile`
VERSION=`perl -ne '/^VERSION\s*=\s*(\S+)/ && print "$1";' Makefile`

for host in araminta sfere; do
  arch=`ssh $host dpkg-architecture -qDEB_HOST_ARCH`
  ssh $host mkdir -p _builds
  scp ${PACKAGE}-${VERSION}.tar.gz $host:_builds/.
  remote $host "rm -rf _builds/${PACKAGE}-${VERSION}"
  remote $host "tar xf ${PACKAGE}-${VERSION}.tar.gz"
  remote $host "cd ${PACKAGE}-${VERSION} && debian/rules build"
  remote $host "cd ${PACKAGE}-${VERSION} && fakeroot debian/rules binary"
  scp $host:_builds/${PACKAGE}_${VERSION}_${arch}.deb .
done
cp ${PACKAGE}_${VERSION}_*.deb $HOME/public_html/web/2009
cp ${PACKAGE}-${VERSION}.tar.gz $HOME/public_html/web/2009
