.TH vcs 1
.SH NAME
\fBvcs\fR [\fIOPTION\fR...] \fICOMMAND\fR [\fIOPTION\fR...] [\fIARGUMENTS\fR...]
.SH DESCRIPTION
.B vcs
guesses what version control system you are using and translates its
own command set accordingly.
.SH OPTIONS
These options are global to
.B vcs
and appear
.I before
the command name.
.TP
.B --verbose\fR, \fB-v
Verbose operation.
.TP
.B --dry-run\fR, \fB-n
Instead of executing native commands, just display them on standard output.
.TP
.B --guess\fR, \fB-g
Identify the native version control system.
Normally this is done silently and automatically; this option displays the
chosen version control system and then exits.
.TP
.B --commands\fR, \fB-H
Displays a list of commands.
.TP
.B --help\fR, \fB-h
Display usage message.
.TP
.B --version\fR, \fB-V
Display version number.
.SH COMMANDS
Commands may be abbreviated to a non-ambiguous prefix.
Commands have their own options which must appear
.I after
the command name.
All commands have a
.B --help
option (not listed below) which summarizes their usage.
.SS add
.B vcs
.B add
.RB [ --binary | -b ]
.IR FILENAME ...
.PP
Subjects the listed files to version control.
The files are not committed.
.PP
.B --binary
indicates that the file should not be translated in any way.
This is suitable for image files, etc.
Note that not every native version control system has a corresponding
option (some prefer to figure it out themselves or do no translation).
In such cases, the \fB--binary\fR option is ignored.
.SS commit
.B vcs
.B commit
.RB [ --message | -m
.IR MESSAGE ]
.RI [ FILENAME ...]
.PP
Commits the listed files, or all modified files if none are listed.
.PP
.B --message
allows the commit message to be set.
If none is specified then an editor is started.
If possible, 
.B vcs
lets the native system invoke the editor rather than doing so itself.
.SS diff
.B vcs
.B diff
.RI [ FILENAME ...]
.PP
Displays differences between the last committed version and the
current checkout.
If no filename is specified then all files are diffed.
Otherwise only the listed files are diffed.
.SS remove
.B vcs
.B remove
.IR FILENAME ...
.PP
Removes the named files.
.SS revert
.B vcs
.B revert
.RI [ FILENAME ...]
.PP
Revert changes to the list files, or to all files if none are listed.
.SH "SUPPORTED VERSION CONTROL SYSTEMS"
This section describes the supported version control systems.
Any issues specific to them are describe here.
.SS CVS
Web page: http://www.nongnu.org/cvs/
.PP
CVS does not auto-detect file types, so use of \fBvcs add --binary\fR
option when adding images files, etc is mandatory.
.SS Bazaar
Web page: http://bazaar-vcs.org/
.SS Subversion
Web page: http://subversion.tigris.org/
.SH "DESIGN PRINCIPLES"
.B vcs
has a deliberately limited command set.
The idea is to reliably support common operations rather than to support
rare operations but only some of the time.
.PP
.B vcs
does not attempt to translate the output of native commands to a
consistent format.
You get what the native system gives you.
