.TH vcs 1
.SH NAME
vcs - version control system wrapper
.SH SYNOPSIS
\fBvcs\fR [\fIOPTION\fR...] \fICOMMAND\fR [\fIOPTION\fR...] [\fIARGUMENTS\fR...]
.SH DESCRIPTION
.B vcs
guesses what version control system you are using and translates its
own command set accordingly.
.SH OPTIONS
These options are global to
.B vcs
and appear
.I before
the command name.
.TP
.B \-\-verbose\fR, \fB\-v
Verbose operation.
.TP
.B \-\-dry-run\fR, \fB\-n
Instead of executing native commands, just display them on standard output.
.TP
.B \-\-guess\fR, \fB\-g
Identify the native version control system.
Normally this is done silently and automatically; this option displays the
chosen version control system and then exits.
.TP
.B \-\-commands\fR, \fB\-H
Displays a list of commands.
.TP
.B \-\-help\fR, \fB\-h
Display usage message.
.TP
.B \-\-version\fR, \fB\-V
Display version number.
.SH COMMANDS
Commands may be abbreviated to a non-ambiguous prefix.
Commands have their own options which must appear
.I after
the command name.
All commands have a
.B \-\-help
option (not listed below) which summarizes their usage.
.SS add
.B vcs
.B add
.RB [ \-\-binary | \-b ]
.IR FILENAME ...
.PP
Subjects the listed files to version control.
The files are not committed.
.PP
.B \-\-binary
indicates that the file should not be translated in any way.
This is suitable for image files, etc.
Note that not every native version control system has a corresponding
option (some prefer to figure it out themselves or do no translation).
In such cases, the \fB--binary\fR option is ignored.
.SS annotate
.B vcs
.B annotate
.I FILENAME
.PP
Outputs the named file with each line annotated with information about
its origin.
Depending on the version control system in used, this will usually
some of the revision number it was last modified in, the date of the
last revision and the user who modified it.
.PP
.B "vcs blame"
is a synonym for
.BR "vcs annotate" .
.SS clone
.B vcs
.B clone
.I URI
.RI [ DIRECTORY ]
.PP
Attempts to deduce what version control system is used by
.IR URI
and check out a copy.
If
.I DIRECTORY
is specified then that is used, otherwise the leaf name of the URI is used.
.PP
In some cases the version control system can be inferred directly from
the URI, for instance if it is a
.B git:
URI.
In other cases
.B vcs
will check for the existence of particular files such as
.B .git
or
.B .bzr
to figure out what
version control system is used.
.PP
Use the
.B -v
option to see details of what it tries, if it isn't working and you
think it should.
.SS commit
.B vcs
.B commit
.RB [ -\-message | \-m
.IR MESSAGE ]
.RI [ FILENAME ...]
.PP
Commits the listed files, or all modified files if none are listed.
.PP
.B \-\-message
allows the commit message to be set.
If none is specified then an editor is started.
If possible, 
.B vcs
lets the native system invoke the editor rather than doing so itself.
.PP
.B "vcs ci"
is a synonym for
.BR "vcs checkin" .
.SS diff
.B vcs
.B diff
.RI [ FILENAME ...]
.PP
Displays differences between the last committed version and the
current checkout.
If no filename is specified then all files are diffed.
Otherwise only the listed files are diffed.
.SS edit
.B vcs
.B edit
.IR FILENAME ...
.PP
Makes files editable.
For most (but not all) version control systems this is not needed and
is a no-op.
.SS log
.B vcs
.B log
.RI [ FILENAME ]
.PP
Display the change history for \fIFILENAME\fR, or for all files if no
file is specified.
(Beware, the latter case is very verbose for CVS!)
.SS remove
.B vcs
.B remove
.RI [ \-\-force | \-f ]
.IR FILENAME ...
.PP
Removes the named files.
.PP
The default behaviour is the same as the native version control system.
For instance if it insists that you delete the files first, or only remove
unchanged files, then so will \fBvcs remove\fR.
.PP
With \fB\-\-force\fR, the files will be deleted and removed from version
control unconditionally.
.PP
.B "vcs rm"
is a synonym for
.BR "vcs remove" .
.SS revert
.B vcs
.B revert
.RI [ FILENAME ...]
.PP
Revert changes to the listed files, or to all files if none are listed.
.PP
Removed files are resurrected and modified files have any changes undone.
Some version control systems will save the modified version to a backup file.
Newly added files are removed from version control and may be deleted
(depending on the underlying version control system).
.PP
Note that not all version control systems can selectively revert
individual files.
.SS status
.B vcs
.B status
.PP
Displays a summary of the current status, showing files that have been
added, edited, removed or are not in version control (and not ignored).
.PP
Note that the output format is that of the native version control
system.
.SS update
.B vcs
.B update
.PP
Updates the working tree to the latest revision.
Note that (currently) it is not possible to update only a subset of files,
or to synchronize to a non-head revision.
.PP
For distributed version control systems this both fetches revisions
from a parent branch and updates your working tree.
.PP
.B "vcs update"
does not attempt to handle conflicts in a uniform way across version
control systems.
You get whatever the underlying system gives you: for instance,
conflict markers in files, or questions asked during update.
You may have to run commands such as
.B "bzr resolve"
to indicate conflicts resolved or
.B "p4 resolve"
to perform conflict resolution tool.
.SH ENVIRONMENT
.TP
.B VCS_PAGER
.TP
.B VCS_DIFF_PAGER
.B "vcs diff"
will filter its output through \fBVCS_DIFF_PAGER\fR or, if that is not
set, \fBVCS_PAGER\fR.
.B "vcs log"
and
.B "vcs annotate"
will filter their output through \fBVCS_PAGER\fR.
.IP
The pager command is executed via the shell.
In both cases no filter will be done executed if standard output is
not a terminal.
.IP
You might, for example, set these as follows:
.IP
.B "VCS_PAGER=less"
.br
.B "VCS_DIFF_PAGER=\(aqcolordiff|less -R\(aq"
.SH "SUPPORTED VERSION CONTROL SYSTEMS"
This section describes the supported version control systems.
Any issues specific to them are describe here.
.SS CVS
Web page: http://www.nongnu.org/cvs/
.PP
CVS does not auto-detect file types, so use of \fBvcs add \-\-binary\fR
option when adding images files, etc is mandatory.
.SS Bazaar
Web page: http://bazaar\-vcs.org/
.SS Subversion
Web page: http://subversion.tigris.org/
.SS Git
Web page: http://git\-scm.com/
.PP
.B vcs
has a more CVS-like model than Git; therefore
.B "vcs commit"
will commit all your changes, not just those mentioned with
.BR "git add" .
.PP
.B "vcs revert"
will delete newly added files.
.SS Mercurial
Web page: http://www.selenic.com/mercurial/
.SS Darcs
Web page: http://darcs.net/
.SS Perforce
Web page: http://www.perforce.com/
.PP
.B "vcs edit"
(or
.BR "p4 edit" )
is required before editing existing files.
.PP
Commands that apply to multiple files are applied only to files in or
below the current directory.
The only exception to this is \fBvcs log\fR which applies to the whole
depot.
.PP
.B "vcs status"
produces CVS-like output summarizing which files are open and which are
unknown to Perforce.
The characters at the start of each line have the following meaning:
.TP
.B A
File is opened for add.
.TP
.B E
File is opened for edit.
.TP
.B D
File is opened for delete.
.TP
.B B
File is opened for branch.
.TP
.B I
File is opened for integrate.
.TP
.B ?
File is unknown to Perforce (and not ignored).
.PP
You can put filenames or glob patterns in
.I .vcsignore
in each directory, or in your home directory, to hide files that
would otherwise show up as
.BR ? .
If you ignore a file that is known to Perforce then a warning is printed.
.PP
Perforce will only be detected if at least one of
.BR P4PORT ,
.B P4CONFIG
or
.B P4CLIENT
is set, and detection works by invoking
.B "p4 changes"
to see if the current directory is inside a P4 workspace.
.SH "DESIGN PRINCIPLES"
.B vcs
has a deliberately limited command set.
The idea is to reliably support common operations rather than to support
rare operations but only some of the time.
.PP
.B vcs
is not intended to give exactly identical semantics for every version
control system, just essentially similar ones.
.PP
.B vcs
does not usually attempt to translate the output of native commands to a
consistent format.
As a rule you get what the native system gives you.
.P
.B vcs
is intended to be useful rather than to adhere to arbitrary rules.
.SH AUTHOR
Richard Kettlewell <rjk@greenend.org.uk>
.PP
The VCS home page is:
.B http://www.greenend.org.uk/rjk/2009/vcs.html
