#! /bin/sh
# This file is part of VCS
# Copyright (C) 2009 Richard Kettlewell
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
set -e

. ${top_srcdir:-.}/tests/utils.sh

t_init bzr http://www.greenend.org.uk/rjk/bzr/vcs.rel

x vcs -n clone http://www.greenend.org.uk/rjk/bzr/vcs.rel
if [ -d vcs.rel ]; then
  echo "dry-run clone created target directory" >&2
  ls -ld vcs.rel
  exit 1
fi

x vcs -v clone http://www.greenend.org.uk/rjk/bzr/vcs.rel
if [ -d vcs.rel ]; then
  :
else
  echo "clone didn't create target directory" >&2
  exit 1
fi

t_done
