#! /bin/sh
# This file is part of VCS
# Copyright (C) 2009 Richard Kettlewell
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
set -e

. $srcdir/tests/utils.sh

EMAIL=vcs@rjk.greenend.org.uk.invalid
export EMAIL

t_init darcs

mkdir project
cd project
x darcs init
cd ..
t_populate

x darcs get project copy
t_verify

t_modify
t_update
t_verify

t_revert
cd copy
cd ..

t_done
