#! /bin/sh
# This file is part of VCS
# Copyright (C) 2009 Richard Kettlewell
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
set -e

. $srcdir/tests/utils.sh

t_init git

mkdir project
cd project
x git init-db
cd ..
t_populate

x git clone project copy
t_verify

t_modify
t_update
t_verify

t_revert
cd copy
if git log three >/dev/null 2>&1; then
  echo 'three still known to git' >&2
  exit 1
fi

touch -- -addme
vcs -v add -- -addme
cd ..

vcs clone http://www.greenend.org.uk/rjk/git/astrosim

t_done
