#! /bin/sh
# This file is part of VCS
# Copyright (C) 2009, 2014 Richard Kettlewell
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
set -e

. ${srcdir:-.}/utils.sh

t_init hg http://www.greenend.org.uk/rjk/2009/mercurial

# This test is currently broken on old versions of Mercurial
v=`hg --version |
     grep '^Mercurial.*version' |
     sed 's/^.*(version //;s/).*//'`
case $v in
0.[789]* )
  exit 77
  ;;
esac

x vcs -n clone static-http://www.greenend.org.uk/rjk/2009/mercurial
if [ -d mercurial ]; then
  echo "dry-run clone created target directory" >&2
  ls -ld mercurial
  exit 1
fi

x vcs -v clone static-http://www.greenend.org.uk/rjk/2009/mercurial
if [ -d mercurial ]; then
  :
else
  echo "clone didn't create target directory" >&2
  exit 1
fi

t_done
