#! /bin/sh
# This file is part of VCS
# Copyright (C) 2009-2011 Richard Kettlewell
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
set -e

. ${top_srcdir:-.}/tests/utils.sh

# bzr-specific setup
BZR_EMAIL=just.testing@example.com
export BZR_EMAIL

# Check dependencies
t_init bzr

# Create test project
x bzr init project
t_populate

# Duplicate it
x vcs clone project copy
t_verify

# Test modification and update
t_modify
t_update
t_verify

# Test revert
t_revert
cd copy
if bzr log three >/dev/null 2>&1; then
  echo 'three still known to bzr' >&2
  exit 1
fi
cd ..

# Test rename
t_rename

t_done
