#! /bin/sh
# This file is part of VCS
# Copyright (C) 2009-2011 Richard Kettlewell
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
set -e

. ${top_srcdir:-.}/tests/utils.sh

# Check dependencies
t_init cvs

# CVS-specific setup
CVSROOT=$testdir/repo
export CVSROOT

# Create repository
x mkdir $CVSROOT
x cvs -d $CVSROOT init

# Create test project
x mkdir $CVSROOT/project
x cvs co project
t_populate

# Duplicate it
x cvs co -d copy project
t_verify

# Test modification and update
t_modify
t_update
t_verify

# Test revert
t_revert
cd copy
x cvs -n up three
status=$(cvs -n up three 2>/dev/null)
if test "x$status" != 'x'; then
    fatal "Did not properly revert 'three'"
fi
cd ..

# Extra update testing for CVS
cd project
echo a >> one
x vcs commit -m "add a to one"

cd ../copy
echo b >> one
x vcs up
x vcs revert one
cat >one.expected <<EOF
one
oneone
a
EOF
check_match one.expected one
x cvs -n up one
status=$(cvs -n up one 2>/dev/null)
if test "x$status" != 'x'; then
    fatal "Did not properly revert 'one'"
fi
cd ..

# CVS does not support renaming
#t_rename

# Test awkward filenames
t_awkward

t_done
