#! /bin/sh
# This file is part of VCS
# Copyright (C) 2009-2011 Richard Kettlewell
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
set -e

. ${top_srcdir:-.}/tests/utils.sh

# Check dependencies
t_init darcs

# darcs-specific setup
EMAIL=vcs@rjk.greenend.org.uk.invalid
export EMAIL

# Create test project
mkdir project
cd project
x darcs init
cd ..
t_populate

# Duplicate it
x darcs get project copy
t_verify

# Test modification and update
t_modify
t_update
t_verify

# Test revert
t_revert

# Test rename
t_rename

# Test awkward filenames
t_awkward

t_done
