#! /bin/sh
# This file is part of VCS
# Copyright (C) 2009 Richard Kettlewell
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
set -e

. ${top_srcdir:-.}/tests/utils.sh

# Check dependencies
#
# (This test can only run if you have p4 and p4d installed.)
t_init p4 p4d

# P4-specific setup

# Create a server
mkdir repo
cd repo
p4d -p 6661 -r . &
p4dpid=$!
cd ..

trap "kill $p4dpid && wait $p4dpid" EXIT INT HUP TERM

export P4PORT=localhost:6661

# Wait for server to come up
while :; do
  if p4 > /dev/null 2>&1; then
    break
  else
    sleep 1
  fi
done

# Create a couple of clients
makep4client client1 $testdir/project
makep4client client2 $testdir/copy

# Create test project
export P4CLIENT=client1
x p4 sync
mkdir project
t_populate

# Duplicate it
export P4CLIENT=client2
x p4 sync
t_verify

# Test modification and update
export P4CLIENT=client1
t_modify

export P4CLIENT=client2
t_update
t_verify

# Test revert
export P4CLIENT=client2
t_revert

# P4-specific testing
#
# Check that awkward filenames are handled correctly
export P4CLIENT=client1
cd project
echo > foo@bar
echo > foo\#bar%wibble\*spong
x vcs -v status
x vcs -v add foo*
x vcs -v commit -m 'files that need encoded names'

# .vcsignore testing
x ln -s target link
x vcs -v status
x vcs -v status > status-output
if grep link status-output >/dev/null; then
  echo "*** unexpectedly found 'link' in status output"
  exit 1
fi
echo > ignoreme
echo ignoreme > .vcsignore
x vcs -v status
vcs -v status > status-output
if grep ignoreme status-output >/dev/null; then
  echo "*** unexpectedly found 'ignoreme' in status output"
  exit 1
fi
if fgrep "? .vcsignore" status-output >/dev/null; then
  :
else
  echo "*** expected '? .vcsignore' in status output"
  exit 1
fi
x vcs -v add .vcsignore
x vcs -v status
x vcs -v status > status-output
if fgrep "A .vcsignore" status-output >/dev/null; then
  :
else
  echo "*** expected 'A .vcsignore' in status output"
  exit 1
fi
x vcs -v commit -m 'Added ignore file'
x vcs -v status
x vcs -v status > status-output
if fgrep ".vcsignore" status-output >/dev/null; then
  echo "*** unexpectedly found '.vcsignore' in status output"
  cat -n status-output
  exit 1
fi
x vcs -v edit .vcsignore
x vcs -v status
x vcs -v status > status-output
if fgrep "e .vcsignore" status-output >/dev/null; then
  :
else
  echo "*** expected 'e .vcsignore' in status output"
  cat -n status-output
  exit 1
fi
x vcs -v revert .vcsignore
x vcs -v remove .vcsignore
x vcs -v status
x vcs -v status > status-output
if fgrep "D .vcsignore" status-output >/dev/null; then
  :
else
  echo "*** expected 'D .vcsignore' in status output"
  cat -n status-output
  exit 1
fi

cd ..

# Test rename
t_rename

t_done

