#! /bin/sh
# This file is part of VCS
# Copyright (C) 2009-2011, 2014 Richard Kettlewell
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
set -e

. ${srcdir:-.}/utils.sh

# Check dependencies
t_init rcs

# Create test project
x mkdir project
x mkdir project/RCS
t_populate

# Duplicate it (using a traditional hack...)
x mkdir copy
x mkdir copy/subdir
x ln -s ../project/RCS copy
x ln -s ../../project/subdir/RCS copy/subdir
x cd copy
x vcs -v update
x cd ..
t_verify

# Test modification
t_modify
t_update
#t_verify              # TODO doesn't work (update can't merge)

# Test revert          # Doesn't work
#t_revert              # (vcs rm is immediate with RCS)

t_awkward

t_done
