#! /bin/sh
# This file is part of VCS
# Copyright (C) 2009 Richard Kettlewell
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
set -e

. ${top_srcdir:-.}/tests/utils.sh

# Check dependencies
t_init svn

# Create repository
repo=$testdir/repo
x svnadmin create $repo

# Create test project
x mkdir project
x svn import -m 'Import empty directory' project file://$repo/trunk/project
x rmdir project
x svn co file:///$repo/trunk/project
t_populate

# Duplicate it
x svn co file:///$repo/trunk/project copy
t_verify

# Test modification and updtae
t_modify
t_update
t_verify

# Test revert
t_revert
cd copy
x svn status three
status=$(svn status three | awk '{print $1}')
if test "x$status" != 'x?'; then
    fatal "Did not properly revert 'three'"
fi
cd ..

# Test rename
t_rename

# Test awkward filenames
t_awkward

t_done
